config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post 'results' => 'home#results'

  get 'results' => 'home#results'
  get 'test' => 'home#test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def results
  	if !params[:term].blank? && !params[:address].blank?

	  	#clears any previous 
		  @restaurants = Restaurant.all
		  @restaurants.destroy_all

    	query = { 
				"term" => params[:term],
				"location" => params[:address],
				"limit" => 18,
				"radius" => 20000,  
			}

			headers = { 
			    "authorization" => "Bearer #{ENV['yelp_token']}",
			}

			response = HTTParty.get("https://api.yelp.com/v3/businesses/search",
			    :query => query,
			    :headers => headers
			)

			#Let figure out how many result came back and 
			length = response["businesses"].length
			count = 0

			#Loop through our response array of hashes and send the records to our database
	  	while count < length do
				@restaurants = Restaurant.create(name: response["businesses"][count]["name"], rating: response["businesses"][count]["rating"], address: response["businesses"][count]["location"]["address1"], address2: response["businesses"][count]["location"]["address2"], address3: response["businesses"][count]["location"]["address3"], city: response["businesses"][count]["location"]["city"], phone: response["businesses"][count]["display_phone"], price: response["businesses"][count]["price"], url: response["businesses"][count]["url"], image: response["businesses"][count]["image_url"] )
				count += 1
			end
			@restaurants = Restaurant.all
		else
	    redirect_to root_path, notice: 'You must provide a food choice and location to eat!'
		end	
	end

  def test
  	#This is where we build our response, hard coding the values for term and location.  
  	#Our yelp_token is safe in application.yml

		query = { 
		  "term" => "greek",
		  "location" => "Atlanta,GA",
		}

		headers = { 
		  "authorization" => "Bearer #{ENV['yelp_token']}",
		}

		response = HTTParty.get("https://api.yelp.com/v3/businesses/search", 
		  :query => query,
		  :headers => headers
		)

		#Let figure out how many result came back and 
		length = response["businesses"].length

		count = 0

		@results = []

		while count < length do

      puts response["businesses"][count]["name"], response["businesses"][count]["location"]["display_address"], response["businesses"][count]["display_phone"], response["businesses"][count]["rating"]
		
			count += 1
		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <div class="well">
      <h1>Let's Find Something to Eat!</h1>
			<div>
    		<%= form_tag results_path do %>
        	<%= text_field_tag :term, nil, placeholder: "What are you hungry for?", class: "form-control" %><br />
        	<%= text_field_tag :address, nil, placeholder:"Where...", class: "form-control" %><br />
        	<%= submit_tag "Feed Me!", class: "btn btn-primary" %>
    		<% end %>
			</div>
    </div>
  </div>
</div>

app/views/home/results.html.erb
<h1>Home#results</h1>
<p>Find me in app/views/home/results.html.erb</p>

<h1>Here's where you can eat <%= params[:term] %> in <%= params[:address] %></h1>

<% if notice  %>
  <p><%= notice %></p>
<% end %>	

<div class="container">
	<div class="row" >
		<% @restaurants.each do |r| %>
			<div class="col-md-4">
				<div class="well center-it">
					<p><%= image_tag r.image, class: "yelp-image" %></p>
	        <h3><%= r.name %></h3>
	        <h4><%= link_to "Visit Profile", r.url %></h4>
	        <p>
	          <%= r.address %>
	        </p>
	        <p>
	          <%= r.address2 %>
	        </p><p>
	          <%= r.address3 %>
	        </p>
	        <p>
	          <%= r.city %>
	        </p>
	        <p>
	          <%= r.phone %>
	        </p>
	        <p>
	          <%= r.price %>
	        </p>
	        <p>
	          <%  r.rating.times do %>
	          	 <span class="glyphicon glyphicon-star"></span>
	          <% end %>	 
	        </p>
	      </div>
      </div>
    <% end %>
  </div>
</div>

<h3>
	<%= link_to "Search Again...", root_path, class: 'btn btn-primary' %>
</h3>

app/views/home/test.html.erb
<h1>Home#test</h1>
<p>Find me in app/views/home/test.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>